YouTube Playlist & Videos catalogue in Port
e-ian/port-doc pull request #1
Opened 2024-11-08 21:10 UTC by e-ian

2024-11-11 00:20 UTC, kodjomiles requested changes

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +## Table of Contents
We don't need table of content. please look at sample guides.

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +- Model playlist and video data using Port blueprints
overview shouldn't be bulleted, let's have an introduction statement

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +## Prerequisites
Again check out sample guide on Port. Prerequisites should be simplified and with this particular assessment you don't need a lot of these

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +
again simplify it

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +### Creating the Playlist Blueprint
talk about the navigation to the page and have a json they can just copy and paste. configure the json blueprint to have your properties

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +#### Playlist Blueprint YAML
the blueprint is not a yaml file. it's a JSON file please check out the docs well

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +identifier: playlist
same as previous comment

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +#### Video Blueprint YAML
same here

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +```
since you had the file written already. you should have called it here in the md.  change this

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +   - The script includes retry logic and rate limiting for API calls
the automation should be done in port like I mentioned

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +4. **Rate Limiting and Quotas**
we don't need to implement rate limiting in this. it's not an integration. it's a self service action or an automation

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +
value preposition should be part of your overview contest. we don't need a separate header for it

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +3. Configure:
the steps should help the client replicate exactly what you've created we will be adding pictures to make this work best. check out sample guides

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +## Relevant Links
remove this please

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +1. **Port Resources**
remove this too, the client doesn't need it

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +Common issues and their solutions:
And this should be removed too

2024-11-11 00:20 UTC, kodjomiles commented on youtube_playlist_data.md
> +## Author
This too should be removed

2024-11-13 16:34 UTC, kodjomiles commented on youtube_playlist_data.md
> +   - Click "Builder" in the left sidebar
Add the link to the Builder page

2024-11-13 16:36 UTC, kodjomiles commented on youtube_playlist_data.md
> +<div class="code-container">
You don't need to write this html. the detail and summary tag will make it a collapsible and If you want it in code just put ```json showLineNumbers  ``` will be fine

2024-11-13 16:36 UTC, kodjomiles commented on youtube_playlist_data.md
> +</div>
remove all html please. it's a markdown

2024-11-13 16:37 UTC, kodjomiles commented on youtube_playlist_data.md
> +   - Click "Builder" in the left sidebar
you can separate this content and let it be under the same header as the data modeling that talks about setting up the blueprints. so you avoid repetition

2024-11-13 16:38 UTC, kodjomiles commented on youtube_playlist_data.md
> +    navigator.clipboard.writeText(code).then(() => {
this will be done for you we don't need to write this code

2024-11-13 16:39 UTC, kodjomiles commented on youtube_playlist_data.md
> +        button.innerText = originalText;
remove this

2024-11-13 16:39 UTC, kodjomiles commented on youtube_playlist_data.md
> +## GitHub Workflow Setup
```suggestion
## GitHub workflow 
```

2024-11-13 16:40 UTC, kodjomiles commented on youtube_playlist_data.md
> +#### Creating the Workflow File
remove this

2024-11-13 16:41 UTC, kodjomiles commented on youtube_playlist_data.md
> +   - Create new file: `ingest.yml` in the directory `.github/workflows`
put this context under workflow and let the needed access keys be an admonition or something

2024-11-13 16:42 UTC, kodjomiles commented on youtube_playlist_data.md
> +  ```yaml copy
this copy ?? not needed

2024-11-14 23:44 UTC, kodjomiles requested changes
Almost there. looking good

2024-11-16 10:19 UTC, kodjomiles reviewed
Go over my reviews and add my suggestions. Almost there

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +<summary>Click to expand Playlist Blueprint JSON</summary>
Make the other ones like this as well please. 
And use capitalization in the titles rather than making all of them start with uppercase, let the first word be the only one starting with uppercase

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +<summary>Click to expand Video Blueprint JSON</summary>
```suggestion
<summary><b> Video blueprint (click to expand) </b></summary>
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +      "title": "Belongs To",
you shouldn't name relationships like this. 
The name of the relationship should have a meaning. this is on the video blueprint so it has a relationship with the playlist. change the name to playlist

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +  - Click on the "+ Action" button to create and new action. Click on "{---} Edit JSON" in the pop up
```suggestion
  - Click on the "+ Action" button to create and new action. 
  - Click on "{---} Edit JSON" in the pop up
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +  - Click on the "+ Action" button to create and new action. Click on "{---} Edit JSON" in the pop up
Make these steps as well

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +  <summary>Click to expand Self-service config JSON</summary>
```suggestion
  <summary><b> Action configuration (click to expand) </b></summary>
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +  - Copy and paste the json configuration details below to setup the Self-Service. Edit with your details.
```suggestion
  - Copy and paste the json configuration details below to setup the Self-Service. 
  :::tip Placeholders
  Remember to replace <YOUR_ORGANISATION_NAME> with your organization name
  <YOUR_REPO_NAME> with your repository name and <SPECIFY_WORKFLOW_FILE> with the name of 
  the workflow
  :::
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +   - Go to your GitHub repository settings
make this steps as well

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +     ```
```suggestion
    
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +     YOUTUBE_API_KEY (Your YouTube Data API key)
```suggestion
     - YOUTUBE_API_KEY (Your YouTube Data API key)
     - PORT_API_KEY (Your Port API key)
     - PORT_CLIENT_ID (Your Port Client ID)
     - PORT_CLIENT_SECRET (Your Port Client Secret)
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +     PORT_API_KEY (Your Port API key)
```suggestion
    
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +     PORT_CLIENT_ID (Your Port Client ID)
```suggestion
     
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +     PORT_CLIENT_SECRET (Your Port Client Secret)
```suggestion
     
```

2024-11-16 10:19 UTC, kodjomiles commented on youtube_playlist_data.md
> +     ```
```suggestion
     
```

2024-11-16 15:37 UTC, PeyGis requested changes
great job. Please go over my comments and apply the fixes

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +real-time performance updates, and automated daily data updates, giving you the insights needed to make informed content decisions.
```suggestion
This guide shows you how to set up a system for tracking YouTube playlists and video performance in Port. 
You’ll learn how to organize your YouTube content, automate the tracking of video metrics, and create visualizations  to monitor playlist growth and audience engagement.
```

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +   - Log into your Port account at [app.getport.io](https://app.getport.io)
this can be merged into 1

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +      },
let's delete this property since every entity is required to have one. so adding this will be redundant

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +    "required": ["title"]
title should be removed

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +  "icon": "Microservice",
change to a better icon other than microservice

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +  "title": "video",
should be capitalized and renamed to YouTube Video

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +  "icon": "Microservice",
change to a better icon. and rename title to  YouTube Playlist

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +      },
delete this since it's redundant

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +      "required": true,
this should be set to false because not every video belongs to a playlist

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +## Self service setup
You can add a one liner explaining why we need a self service action (SSA) for this task

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +   - Create new file: `ingest.yml` in the directory `.github/workflows` and pass the secrets.
rephrase this line. It make readers believe that they need to pass the secret to this file

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +   - Add the following GitHub Actions workflow configuration:
Github Actions workflow is redundant. Could say GitHub workflow

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +                  title: $title,
remove title

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +                        title: $title,
remove title

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +
can we also report success to Port?

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +- When completed, go to catalogue to view the playlist and videos respectively.
catalog instead of catalogue

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +### 1. Video Count Metric
Can you also show the sections where you create the dashboard? what you've shown so far is the dashboard widgets

2024-11-16 15:37 UTC, PeyGis commented on youtube_playlist_data.md
> +</details>
The guide is missing conclusion section

2024-11-18 16:56 UTC, PeyGis requested changes
we're almost there. please check my comments

2024-11-18 22:45 UTC, PeyGis approved these changes
this is all good now. we're in a good shape to submit to Port

2024-11-19 08:56 UTC, PeyGis requested changes
final comments for Ian

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +        "title": "videoCount",
```suggestion
        "title": "Video Count",
```

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +        "title": "thumbnailUrl",
```suggestion
        "title": "Thumbnail Url",
```

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +        "title": "description",
```suggestion
        "title": "Description",
```

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +        "title": "description",
```suggestion
        "title": "Description",
```

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +        "title": "thumbnailUrl",
```suggestion
        "title": "Thumbnail Url",
```

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +    }
just like I've suggested above, the title of the properties should in this format : Video Count, Comment Count, Duration, Description etc

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +      "title": "playlist",
```suggestion
        "title": "Playlist",
```

2024-11-19 08:56 UTC, PeyGis commented on youtube_playlist_data.md
> +          "title": "playlist_id",
```suggestion
        "title": "Playlist ID",
```

2024-11-19 09:12 UTC, merged